baseURL = "https://Cosmo-CoDiOS.github.io/blog"
languageCode = "en-us"
title = "The Cosmo-CoDiOS Project"
theme = "noteworthy"
enableRobotsTXT = true
paginate = 5 # Set the number of posts to show before overflowing to the next page.
summaryLength = 10 # Configure how long the post summary should be on the homepage.

[taxonomies]
  tag = "tags"

[author]
    name = "The Cosmo-CoDiOS Developers"

# Set to false to disallow raw HTML in markdown files
[markup.goldmark.renderer]
    unsafe = false

[params]
    math = false
    
    # Blog description at the top of the homepage. Supports markdown.
    description = "This blog is for the developers of the Cosmo-CoDiOS project to discuss progress, and a way to look behind-the-scenes of the project"

    showReadMore = true

    # Set enableKofi to true to enable the Ko-fi support button. Add your Ko-fi ID to link to your account.
    enableKofi = false
    kofi = ""

    # Programming
    github = "Cosmo-CoDiOS"
#    gitlab = "Cosmo-CoDiOS"

# Menu links along the sidebar navigation.
[[menu.main]]
    identifier = "about"
    name = "About"
    url = "/about/"
    weight = 1 # Weight is an integer used to sort the menu items. The sorting goes from smallest to largest numbers. If weight is not defined for each menu entry, Hugo will sort the entries alphabetically.

[[menu.main]]
    identifier = "tags"
    name = "Tags"
    url = "/tags/"
    weight = 2

[[menu.main]]
    name = "Archives"
    identifier = "archives"
    url = "/archives/"
    weight = 3

# Privacy configurations: https://gohugo.io/about/hugo-and-gdpr/
[privacy]
  [privacy.disqus]
    disable = true
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.instagram]
    disable = true
    simple = false
  [privacy.twitter]
    disable = true
    enableDNT = true
    simple = false
  [privacy.vimeo]
    disable = true
    simple = false
  [privacy.youtube]
    disable = true
    privacyEnhanced = true
